declare module 'card' {
    export interface Position {
        x: number;
        y: number;
    }

    export interface CardElement {
        coordinates: Position;
        matrix: Position;
        position: number;
        value: number;
        delete: boolean;
        visited: boolean;
        uuid: number;
    }
}

declare module 'status' {
    export type Status = {
        inProgress: boolean;
        failed: boolean;
        success: boolean;
    };
}


declare module 'settings' {
    export interface Settings {
        boardSize: number;
        maxValue: number;
        elementsPerAction: number;
        valuesAutoGenerated: Array<2|4>;
    }
}

declare module 'result' {
    export type Result = {
        username: string;
        score: number;
    };
}